apiVersion: v1
kind: Pod
metadata:
  name: admin-front-end-app
  namespace: default
  labels:
    role: admin-front-end
spec:
  containers:
  - name: admin-front-end-app
    image: nginx:latest
    ports:
    - containerPort: 80