apiVersion: v1
kind: Pod
metadata:
  name: back-end-api-app
  namespace: default
  labels:
    role: back-end-api
spec:
  containers:
  - name: back-end-api
    image: nginx:latest
    ports:
    - containerPort: 80